tunnel: 2b59f68e-27b4-4738-afa9-12894418b128
credentials-file: /etc/cloudflared/creds.json
ingress:
  # Ruta por defecto para el simulador
  - hostname: simuladorparametrica.com
    service: http://localhost:3005
  # Regla por defecto para todo lo demás
  - service: http_status:404 