# Configuración de servicios para SasDatQbox
# Compatible con Cloudflare Tunnel

version: '3.8'

services:
  simuladorbrito:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simuladorbrito
    environment:
      - NODE_ENV=production
      - PORT=3005
      - HOST=0.0.0.0
      - NEXT_PUBLIC_ASSET_PREFIX=https://simuladorparametrica.com
    ports:
      - "3005:3005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://0.0.0.0:3005" , "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - simuladorbrito-network
      - lotto-bueno-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: simuladorbrito-cloudflared
    restart: unless-stopped
    depends_on:
      - simuladorbrito
    network_mode: "host"
    command: tunnel --no-autoupdate run --token eyJhIjoiYzMzYWJjZTc5NWQ2MjMxYjE2MWQ1OWYyMmQ0NGRlZTUiLCJ0IjoiMmI1OWY2OGUtMjdiNC00NzM4LWFmYTktMTI4OTQ0MThiMTI4IiwicyI6Ik1qSTRNemc0WkdVdE1qVmtNQzAwTVRRNUxXRTFNbUl0WmpVM05qY3lOelptTURVMCJ9

networks:
  simuladorbrito-network:
    driver: bridge
  lotto-bueno-network:
    external: true