# Configuración de servicios para Simulador Electoral Brito
# Compatible con Cloudflare Tunnel

version: '3.8'

services:
  simuladorbrito:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ASSET_PREFIX: "https://ahorasi.online"
        NEXT_PUBLIC_BASE_URL: "https://ahorasi.online"
        NEXT_PUBLIC_SITE_NAME: "Simulador Electoral José Brito"
        NEXT_PUBLIC_SITE_DESCRIPTION: "Simulador de votación para las elecciones regionales de Anzoátegui 2025"
    container_name: simuladorbrito
    restart: always
    ports:
      - "3005:3005"  # Exponer el puerto 3005 directamente
    environment:
      - NODE_ENV=production
      - PORT=3005
      - HOST=0.0.0.0
      - NEXT_PUBLIC_ASSET_PREFIX=https://ahorasi.online
      - NEXT_PUBLIC_BASE_URL=https://ahorasi.online
      - NEXT_PUBLIC_SITE_NAME=Simulador Electoral José Brito
      - NEXT_PUBLIC_SITE_DESCRIPTION=Simulador de votación para las elecciones regionales de Anzoátegui 2025
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3005" , "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - simuladorbrito-network

  # Nginx para servir como proxy y manejar SSL
  nginx:
    image: nginx:alpine
    container_name: simuladorbrito-nginx
    restart: always
    ports:
      - "8081:80"    # Puerto 8081 para HTTP
      - "8443:443"  # Puerto 8443 para HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      # Usar los certificados existentes en lugar de los de certbot
      - ../nginx/certs/ahorasi.fullchain.pem:/etc/nginx/ssl/ahorasi.fullchain.pem:ro
      - ../nginx/certs/ahorasi.privkey.pem:/etc/nginx/ssl/ahorasi.privkey.pem:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - simuladorbrito
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80" , "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - simuladorbrito-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  simuladorbrito-network:
    driver: bridge
    # Configuraciones adicionales para mejorar la comunicación entre contenedores
    ipam:
      config:
        - subnet: 172.28.0.0/16