# Configuración de servicios para Simulador Electoral Brito
# Compatible con Cloudflare Tunnel

services:
  simuladorbrito:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simuladorbrito
    restart: always
    ports:
      - "3005:3005"  # Exponer el puerto 3005 directamente
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3005" , "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - simuladorbrito-network

  # Nginx para servir como proxy y manejar SSL
  nginx:
    image: nginx:alpine
    container_name: simuladorbrito-nginx
    restart: always
    ports:
      - "8081:80"    # Puerto 8081 para HTTP
      - "8443:443"  # Puerto 8443 para HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      # Usar los certificados existentes
      - ../nginx/certs/ahorasi.fullchain.pem:/etc/nginx/ssl/ahorasi.fullchain.pem:ro
      - ../nginx/certs/ahorasi.privkey.pem:/etc/nginx/ssl/ahorasi.privkey.pem:ro
      # Limpiar el default.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - simuladorbrito
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost" , "||", "exit", "0"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - simuladorbrito-network
    # Comando para mantener Nginx actualizado y funcionando
    command: "/bin/sh -c 'nginx -t && nginx -g \"daemon off;\"'"

networks:
  simuladorbrito-network:
    driver: bridge
    # Configuraciones adicionales para mejorar la comunicación entre contenedores
    ipam:
      config:
        - subnet: 172.28.0.0/16