global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Usar nombre de servicio

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Usar nombre de servicio

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # Usar nombre de servicio 

  - job_name: 'api-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000'] # Usar nombre de servicio de la API 